"use strict";

/**
 * End-to-end install test: runs the full setup script as a real subprocess
 * (`--yes --user --passdir`) with a mocked toolchain, then asserts that the
 * bootstrap host, the native manifest, and a parcelrc (with the resolved
 * PASSWORD_STORE_DIR) were produced and both smoke tests passed.
 *
 * A staged smoke-test double is installed as BOOTSTRAP_HOST: it creates a
 * minimal default parcelrc and exits 0, so the cold-start / verification smoke
 * tests pass without a real GPG keyring or password store.
 *
 * @since 1.0.7
 */

import { test } from "node:test";
import assert from "node:assert";
import { mkdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import { runBash, SETUP_SCRIPT, makeTempHome, writeMockBin } from "./harness.js";

// A browser/app the installer will detect via a fixture path we create.
const HOST_NAME = "com.github.erayd.parcel";
const EXT_CHROMIUM = "ciifpadakeohfnnneflckhojbldkkllp";

/**
 * Content of the staged bootstrap host. Resolves CONFIG_DIR exactly as the real
 * host does, creates a default parcelrc (with commented GPG/JQ/OPENSSL/
 * PASSWORD_STORE_DIR/HOST_HASH defaults so set_parcelrc_var inserts below them),
 * and exits 0.
 */
const BOOTSTRAP_HOST = `#!/usr/bin/env bash
# Test double for the signed bootstrap host: creates a default parcelrc and exits 0.
if [[ "\${XDG_CONFIG_HOME:-}" == /* ]]; then
    CONFIG_DIR="$XDG_CONFIG_HOME/parcel"
else
    CONFIG_DIR="$HOME/.config/parcel"
fi
mkdir -p "$CONFIG_DIR"
if [ ! -e "$CONFIG_DIR/parcelrc" ]; then
    cat > "$CONFIG_DIR/parcelrc" <<'EOT'
# parcelrc (auto-generated by the bootstrap host)
#GPG="gpg"
#JQ="jq"
#OPENSSL="openssl"
#PASSWORD_STORE_DIR="$HOME/.password-store"
#HOST_HASH=""
EOT
    chmod 0600 "$CONFIG_DIR/parcelrc"
fi
exit 0
`;

/**
 * Build the bash command + env for one full `main` run and invoke it.
 * @param {string[]} args - Extra CLI arguments (e.g. ["--uninstall", "--remove-config"]).
 * @param {Record<string, string>} env - Child environment (bin PATH already prepared by caller).
 * @returns {{stdout:string, stderr:string, code:number|null}} Result tuple.
 * @since 1.0.7
 */
function runSetup(args, env) {
    const cmd = [`"${SETUP_SCRIPT}"`].concat(args.map((a) => `"${a}"`)).join(" ");
    return runBash(cmd, { env });
}

/** Verifies a complete --yes --user install produces the host binary, manifest, and parcelrc. */
test("full --yes --user install installs the host, manifest, and parcelrc; smoke tests pass", () => {
    const { home, cleanup } = makeTempHome();
    try {
        // A detected-browser fixture path, a custom password store, and mocked tools.
        const chromeApp = join(home, "chrome-app");
        mkdirSync(chromeApp, { recursive: true });
        const pass = join(home, "password-store");
        mkdirSync(pass, { recursive: true });

        const bin = join(home, "bin");
        writeMockBin(bin, "uname", "echo Linux");
        writeMockBin(bin, "gpg", `[ "\${1:-}" = "--version" ] && echo "gpg (GnuPG) 2.4.0"`);
        writeMockBin(bin, "flatpak", "exit 0");

        const config = {
            hostName: HOST_NAME,
            extensionIds: { chromium: EXT_CHROMIUM, firefox: "parcel@erayd.net" },
            browsers: [
                {
                    name: "chrome",
                    engine: "chromium",
                    detect: { linux: [chromeApp] },
                    manifestDir: { "linux-user": "~/.config/chrome-test/NativeMessagingHosts" },
                },
            ],
            flatpak: { browsers: [], wrapperDirTemplate: "~/.var/app/{appId}/config/parcel" },
        };

        const res = runSetup(["--yes", "--user", "--passdir", "$PARCEL_TEST_PASSDIR"], {
            PATH: `${bin}:${process.env.PATH}`,
            HOME: home,
            TMPDIR: home,
            BOOTSTRAP_HOST,
            SETUP_CONFIG: JSON.stringify(config),
            SIGNED_HOST_SHA256: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
            PARCEL_TEST_PASSDIR: pass,
        });

        assert.strictEqual(res.code, 0, `install must exit 0 (stderr:\n${res.stderr})`);

        // Bootstrap host installed and executable.
        const hostBin = join(home, ".local", "bin", "parcel-host");
        assert.ok(statSync(hostBin).isFile(), "bootstrap host must be installed");
        assert.strictEqual(statSync(hostBin).mode & 0o777, 0o755, "host must be 0755");
        assert.strictEqual(readFileSync(hostBin, "utf8"), BOOTSTRAP_HOST, "installed host must match the staged double");

        // Native manifest written and well-formed.
        const manifestPath = join(home, ".config", "chrome-test", "NativeMessagingHosts", `${HOST_NAME}.json`);
        const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
        assert.strictEqual(manifest.name, HOST_NAME, "manifest name must match the host name");
        assert.strictEqual(manifest.path, hostBin, "manifest path must point at the installed host");
        assert.strictEqual(manifest.type, "stdio");
        assert.deepStrictEqual(manifest.allowed_origins, [`chrome-extension://${EXT_CHROMIUM}/`]);

        // parcelrc created (0600) with the custom password store persisted.
        const parcelrc = join(home, ".config", "parcel", "parcelrc");
        assert.strictEqual(statSync(parcelrc).mode & 0o777, 0o600, "parcelrc must be 0600");
        assert.ok(readFileSync(parcelrc, "utf8").includes(`PASSWORD_STORE_DIR="${pass}"`), "parcelrc must persist the resolved store");

        assert.match(res.stderr, /Second smoke test passed/, "the verification smoke test must pass");
    } finally {
        cleanup();
    }
});
