#!/usr/bin/env bash
set -euo pipefail

# ISC License
#
# Copyright (c) 2023-2026 Erayd LTD
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Generate the distributable parcel-setup.sh by prepending a heredoc preamble
# to src/parcel-setup.sh.
#
# The preamble sets three variables:
#   BOOTSTRAP_HOST      - contents of the repo-root bootstrap host (parcel-host)
#   SETUP_CONFIG        - contents of src/parcel-setup.json
#   SIGNED_HOST_SHA256  - SHA256 of src/parcel-host (the signed host)
#
# @since 1.0.7

cd "$(dirname "$0")/.."

# Compute SHA256 of the signed host
HASH_BIN="$(command -v sha256sum 2>/dev/null || command -v sha256 2>/dev/null)"
if [ -z "$HASH_BIN" ]; then
    echo "Error: neither sha256sum nor sha256 found" >&2
    exit 1
fi
SIGNED_HOST_SHA256="$("$HASH_BIN" src/parcel-host | awk '{print $1}')"

# Generate the output file
OUT="parcel-setup.sh"

{
    echo '#!/usr/bin/env bash'
    echo ''
    echo '# Generated by make setup — do not edit directly.'
    echo '# This file is a build artifact. Edit src/parcel-setup.sh instead.'
    echo ''

    # Embed the bootstrap host using a quoted heredoc (no expansion)
    printf "BOOTSTRAP_HOST=\"\$(cat <<'__PARCEL_BOOTSTRAP_HOST__'\n"
    cat parcel-host
    printf '\n__PARCEL_BOOTSTRAP_HOST__\n)"\n'

    # Embed the setup config using a quoted heredoc
    printf "SETUP_CONFIG=\"\$(cat <<'__PARCEL_SETUP_CONFIG__'\n"
    cat src/parcel-setup.json
    printf '\n__PARCEL_SETUP_CONFIG__\n)"\n'

    # Embed the signed host hash
    printf 'SIGNED_HOST_SHA256="%s"\n' "$SIGNED_HOST_SHA256"

    echo ''

    # Append the setup script body (skip the shebang line)
    tail -n +2 src/parcel-setup.sh
} > "$OUT"

chmod +x "$OUT"

echo "Generated $OUT"
echo "  Bootstrap host: $(wc -l < parcel-host) lines embedded"
echo "  Setup config:   $(wc -l < src/parcel-setup.json) lines embedded"
echo "  Signed host hash: $SIGNED_HOST_SHA256"
