#!/usr/bin/env bash
set -e

# ISC License
#
# Copyright (c) 2023-2026 Erayd LTD
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# set up the environment
TOKEN="broadcast"
ALLOWED_FILES=()
if [ ! -d "$PASSWORD_STORE_DIR" ]; then
    parcel_error "Invalid password store directory: $PASSWORD_STORE_DIR" 1
fi
PARCELFILE="$PASSWORD_STORE_DIR/.parcel.json"
CONFIG="{}"
CONFIG_MODIFIED=0

function get_mtime() {
    stat -L -c %Y "$1" 2>/dev/null || stat -L -f %m "$1"
}

# load the configuration
function load_config() {
    if [ -f "$PARCELFILE" ]; then
        if ! CONFIG="$(cat "$PARCELFILE")"; then
            parcel_error "Failed to read config file: $PARCELFILE" 1
        fi
        CONFIG_MODIFIED="$(get_mtime "$PARCELFILE")"
    else
        CONFIG="{}"
        CONFIG_MODIFIED="$(date +%s)"
    fi
    local REALPASSDIR="$(readlink -f "$PASSWORD_STORE_DIR")"
    if ! CONFIG="$(jq --arg passdir "$PASSWORD_STORE_DIR" --arg realPassdir "$REALPASSDIR" --arg mtime "$CONFIG_MODIFIED" '. + {modified: ($mtime|tonumber)} + {passdir: $passdir} + {realPassdir: $realPassdir} + (if has("rules") then null else {rules:[{pattern:"."}]} end)' <<< "$CONFIG")"; then
        parcel_error "Failed to parse config file: $PARCELFILE" 1
    fi
}

# ensure that the config is up to date
function update_config() {
    if [[ ! -f "$PARCELFILE" || -f "$PARCELFILE" && "$CONFIG_MODIFIED" -ne "$(get_mtime "$PARCELFILE")" ]]; then
        load_config
        action_list >/dev/null
    fi
}

# get the current config
function action_configure() {
    update_config
    parcel_send "$CONFIG"
}

# check whether there have been any changes to the password store since the last time the list was generated
function action_changes_since() {
    update_config
    local SINCE="$(jq -r '.since' <<< "$1")"
    if [[ -z "$SINCE" || "$SINCE" == "null" || ! "$SINCE" =~ ^[0-9]{10}$ ]]; then
        parcel_error "Invalid timestamp: $SINCE"
    fi
    SINCE="$(date -d "$SINCE" +'%Y-%m-%d %H:%M:%S' 2>/dev/null || date -j -f "%s" "$SINCE" +'%Y-%m-%d %H:%M:%S')"
    CHANGES=$(find -L "$PASSWORD_STORE_DIR" \( -type d -name '.git' -prune \) -o \( -type d -not -path "$PASSWORD_STORE_DIR/.*" -not -path "$PASSWORD_STORE_DIR/**/.*" -newermt "$SINCE" -print \) | wc -l)
    parcel_send "$(jq -n --arg changes "$CHANGES" '{changes: ($changes|gsub("\\s+"; "")|tonumber)}')"
}

# get a list of all the password entries which match the config
function action_list() {
    update_config
    local MIXED="$(
        {
            find -L "$PASSWORD_STORE_DIR" \( -type d -name '.git' -prune \) -o \( \( -type f -o -type l \) -not -path "$PASSWORD_STORE_DIR/.*" -not -path "$PASSWORD_STORE_DIR/**/.*" -name '*.gpg' -print \)
        } 2>&1 || true
    )"
    local FIND_OUT=""
    local FIND_ERR=""
    while true; do
        IFS= read -r line <<< "" || break
        IFS= read -r line || break
        if [[ "$line" == "find:"* ]]; then
            FIND_ERR+="$line"$'\n'
        else
            FIND_OUT+="$line"$'\n'
        fi
    done <<< "$MIXED"
    if [ -n "$FIND_ERR" ]; then
        parcel_error "Unable to scan files: $FIND_ERR"
        return 0
    fi
    local REAL_OUT="$(printf '%s' "$FIND_OUT" | tr '\n' '\0' | xargs -0 -n100 readlink -f || true)"
    local SYMLINKS=()
    while IFS= read -r link; do
        if [ -n "$link" ]; then
            SYMLINKS+=("$link/")
        fi
    done < <(find "$PASSWORD_STORE_DIR" -not -path "$PASSWORD_STORE_DIR/.*" -not -path "$PASSWORD_STORE_DIR/**/.*" -type l -print)
    local IS_LINK=""
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            local linked=0
            if test -L "$line"; then
                linked=1
            else
                for prefix in "${SYMLINKS[@]}"; do
                    if [[ "$line" == "$prefix"* ]]; then
                        linked=1
                        break
                    fi
                done
            fi
            IS_LINK+="$linked"$'\n'
        fi
    done <<< "$FIND_OUT"
    local OUT="$(
            jq -n --rawfile path <(echo "$FIND_OUT") --rawfile real <(echo "$REAL_OUT") --rawfile is_link <(echo "$IS_LINK") '
                [$path, $real, $is_link]
                | map(rtrimstr("\n") | split("\n") | map(select(length > 0)))
                | transpose
                | map({path: .[0], real: .[1], is_link: (.[2] | tonumber)})
                | {entries: .}
                ' |
            jq -s '
                .[0] * .[1]
                | . as $top
                | ($top.rules|map(select(.ignore==false or (has("ignore") | not)).pattern)) as $include
                | ($top.rules|map(select(.ignore==true).pattern)) as $ignore
                | .entries | (
                    map(
                        .={path: .path, name: .path | sub("^" + $top.passdir + "/"; "")|sub(".gpg$"; ""), is_link: .is_link, real: .real}
                        | . as $entry
                        | select(
                            reduce $include[] as $pattern (false; . or ($entry.name|test($pattern)))
                            and (reduce $ignore[] as $pattern (false; . or ($entry.name|test($pattern)))|not)
                            and (
                                ($entry.is_link == 0)
                                or (
                                    ($top.allowLinks == true) and (
                                        ($entry.real | startswith($top.realPassdir))
                                        or (($entry.real | startswith($top.realPassdir) | not) and $top.allowExternalLinks == true)
                                    )
                                )
                            )
                        )
                    )
                    | sort_by(.name)

                )
            ' \
                <(echo "$CONFIG") -
    )"

    # kludgery required to set a global array's content using a string of single-quoted strings
    declare -a LOCAL_AF="( $(jq -rc 'map(.path) | @sh' <<< "$OUT") )"
    ALLOWED_FILES=( "${LOCAL_AF[@]}" )

    parcel_send "$OUT"
}

# audit a decryption attempt
function audit_decrypt() {
    local SHOULD_AUDIT="$(jq -r '.auditDecrypt' <<< "$CONFIG")"
    if [ "$SHOULD_AUDIT" != "true" ]; then
        return 0
    fi
    local FILE_PATH="$1"
    local TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    local MESSAGE="$2"
    local INTENT="$3"
    local ORIGIN="$4"
    echo "[$TIMESTAMP] DECRYPT $INTENT $ORIGIN $FILE_PATH: $MESSAGE" >&5
}

# decrypt and return the contents of a password entry
function action_decrypt() {
    update_config
    local FILE_PATH="$(jq -r '.path' <<< "$1")"
    local INTENT="$(jq -r '.intent' <<< "$1")"
    local ORIGIN="$(jq -r '.origin' <<< "$1")"
    local ALLOW=0
    local OUT
    for ALLOWED in "${ALLOWED_FILES[@]}"; do
        if [ "$ALLOWED" = "$FILE_PATH" ]; then
            ALLOW=1
            break
        fi
    done
    if [ $ALLOW -ne 1 ]; then
        audit_decrypt "$FILE_PATH" "Denied (path out of scope)" "$INTENT" "$ORIGIN"
        parcel_error "Access Denied: Path out of scope: $FILE_PATH"
        return 0
    fi
    if [ ! -f "$FILE_PATH" ]; then
        audit_decrypt "$FILE_PATH" "File not found" "$INTENT" "$ORIGIN"
        parcel_error "File not found: $FILE_PATH"
        return 0
    fi
    if ! OUT="$(gpg --decrypt --quiet --batch --no-tty --yes < "$FILE_PATH" 2>/dev/null)"; then
        audit_decrypt "$FILE_PATH" "Decryption failed" "$INTENT" "$ORIGIN"
        parcel_error "Failed to decrypt $FILE_PATH"
        return 0
    fi
    audit_decrypt "$FILE_PATH" "Success" "$INTENT" "$ORIGIN"
    parcel_send "$(jq -n --arg path "$FILE_PATH" --arg plaintext "$OUT" '{path: $path, plaintext: $plaintext}')"
}
